name: "Quarterly Report Update on the 1st of Each Month"
on:
  schedule:
    - cron: "0 1 1 * *"
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Runs script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Generate a classic token, add it to Actions secrets, and use it in this field
          GITHUB_OWNER_FOR_ISSUE: "owner" # Make sure to specify the owner of the repository where the issue will be created
          GITHUB_REPO_FOR_ISSUE: "repo" # Make sure to specify the name of the repository where the issue will be created
          GITHUB_OWNERS_REPOS: "owner/repo" # Be sure to list the owner and repository name in the format owner/repo
          LABELS: "Report"
          ASSIGNEES: "user-1, user-2, user-3"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Berlin"
          REPORT_PERIOD: "months:3"
          AGGREGATE_VALUE_METHODS: average
          SHOW_STATS_TYPES: timeline
          PERIOD_SPLIT_UNIT: none
          TOP_LIST_AMOUNT: 5
          EXECUTION_OUTCOME: existing-issue
          ISSUE_NUMBER: 1
