name: "Yearly Statistics Update Every Weekday"
on:
  schedule:
    - cron: "0 23 * * 1,2,3,4,5"
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Runs script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Generate a classic token, add it to Actions secrets, and use it in this field
          GITHUB_OWNER_FOR_ISSUE: "owner" # Make sure to specify the owner of the repository where the issue will be created
          GITHUB_REPO_FOR_ISSUE: "repo" # Make sure to specify the name of the repository where the issue will be created
          GITHUB_OWNERS_REPOS: "owner/repo" # Be sure to list the owner and repository name in the format owner/repo
          LABELS: "Report"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Berlin"
          REPORT_DATE_START: 01/01/2024
          TOP_LIST_AMOUNT: 5
          SHOW_USERS: total
          EXECUTION_OUTCOME: existing-issue
          ISSUE_NUMBER: 1 # Set issue number or change EXECUTION_OUTCOME to new-issue
